import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../../database/prisma.service';

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generateDailySiteReport(siteId: string): Promise<Buffer> {
    const site = await this.prisma.site.findUnique({
      where: { id: siteId },
      include: { client: true },
    });

    if (!site) throw new Error('Site not found');

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });

      // Header
      doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Daily Operations Report', { align: 'center' });
      doc.moveDown(2);

      // Site Info
      doc.fontSize(12).font('Helvetica-Bold').text(`Site: ${site.name}`);
      doc.font('Helvetica').text(`Client: ${site.client.companyName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Risk Level: ${site.riskLevel}`);
      doc.moveDown(2);

      // Section: Attendance Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Attendance Summary');
      doc.font('Helvetica').text('Present: 14 / 15');
      doc.text('Late: 1');
      doc.text('Absent: 0');
      doc.moveDown();

      // Section: Incident Log
      doc.fontSize(14).font('Helvetica-Bold').text('Incident Log');
      doc.font('Helvetica').text('No critical incidents reported today.');
      doc.moveDown();

      // Footer
      doc.fontSize(10).fillColor('gray').text(
        'This document is auto-generated by Spectra Operations Intelligence Platform.',
        50,
        750,
        { align: 'center', width: 500 }
      );

      doc.end();
    });

    return pdfBuffer;
  }
}
