import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../../database/prisma.service';

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generateDailySiteReport(siteId: string): Promise<Buffer> {
    const site = await this.prisma.site.findUnique({
      where: { id: siteId },
      include: { client: true },
    });

    if (!site) throw new NotFoundException('Site not found');

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const [
      todayAttendance,
      totalGuards,
      todayIncidents,
      lateCount,
      absentCount,
    ] = await Promise.all([
      this.prisma.attendance.count({
        where: { siteId, checkInTime: { gte: today } },
      }),
      this.prisma.guard.count({
        where: { assignedSiteId: siteId, status: 'ACTIVE' },
      }),
      this.prisma.incident.count({
        where: { siteId, reportedAt: { gte: today } },
      }),
      this.prisma.attendance.count({
        where: { siteId, checkInTime: { gte: today }, isLate: true },
      }),
      this.prisma.attendance.count({
        where: { siteId, isAbsent: true },
      }),
    ]);

    const recentIncidents = await this.prisma.incident.findMany({
      where: { siteId, reportedAt: { gte: today } },
      take: 10,
      orderBy: { reportedAt: 'desc' },
      select: { title: true, incidentType: true, severity: true },
    });

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Daily Operations Report', { align: 'center' });
      doc.moveDown(2);

      // Site Info
      doc.fontSize(12).font('Helvetica-Bold').text(`Site: ${site.name}`);
      doc.font('Helvetica').text(`Client: ${site.client.companyName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Risk Level: ${site.riskLevel}`);
      doc.moveDown(2);

      // Attendance Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Attendance Summary');
      doc
        .font('Helvetica')
        .text(`Present: ${todayAttendance} / ${totalGuards}`);
      doc.text(`Late: ${lateCount}`);
      doc.text(`Absent: ${absentCount}`);
      doc.moveDown();

      // Incident Log
      doc.fontSize(14).font('Helvetica-Bold').text('Incident Log');
      if (recentIncidents.length === 0) {
        doc.font('Helvetica').text('No incidents reported today.');
      } else {
        for (const inc of recentIncidents) {
          doc
            .font('Helvetica')
            .text(`- [${inc.severity}] ${inc.incidentType}: ${inc.title}`);
        }
      }
      doc.moveDown();

      // Footer
      doc
        .fontSize(10)
        .fillColor('gray')
        .text(
          'This document is auto-generated by Spectra Operations Intelligence Platform.',
          50,
          750,
          { align: 'center', width: 500 },
        );

      doc.end();
    });

    return pdfBuffer;
  }

  async generateWeeklySiteReport(siteId: string): Promise<Buffer> {
    const site = await this.prisma.site.findUnique({
      where: { id: siteId },
      include: { client: true },
    });
    if (!site) throw new NotFoundException('Site not found');

    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    weekAgo.setHours(0, 0, 0, 0);

    const [
      weeklyAttendance,
      weeklyIncidents,
      patrolCount,
    ] = await Promise.all([
      this.prisma.attendance.count({
        where: { siteId, checkInTime: { gte: weekAgo } },
      }),
      this.prisma.incident.findMany({
        where: { siteId, reportedAt: { gte: weekAgo } },
        orderBy: { reportedAt: 'desc' },
        select: { title: true, incidentType: true, severity: true, reportedAt: true },
      }),
      this.prisma.patrolRecord.count({
        where: { route: { siteId }, startTime: { gte: weekAgo } },
      }),
    ]);

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Weekly Operations Report', { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(12).font('Helvetica-Bold').text(`Site: ${site.name}`);
      doc.font('Helvetica').text(`Client: ${site.client.companyName}`);
      doc.text(`Period: ${weekAgo.toLocaleDateString()} - ${new Date().toLocaleDateString()}`);
      doc.text(`Risk Level: ${site.riskLevel}`);
      doc.moveDown(2);

      doc.fontSize(14).font('Helvetica-Bold').text('Weekly Summary');
      doc.font('Helvetica').text(`Total Attendance Records: ${weeklyAttendance}`);
      doc.text(`Total Patrols Completed: ${patrolCount}`);
      doc.text(`Total Incidents Reported: ${weeklyIncidents.length}`);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Incident Log');
      if (weeklyIncidents.length === 0) {
        doc.font('Helvetica').text('No incidents reported this week.');
      } else {
        for (const inc of weeklyIncidents) {
          doc.font('Helvetica')
            .text(`- [${inc.severity}] ${inc.incidentType}: ${inc.title} (${new Date(inc.reportedAt).toLocaleDateString()})`);
        }
      }
      doc.moveDown();

      doc.fontSize(10).fillColor('gray')
        .text('This document is auto-generated by Spectra Operations Intelligence Platform.', 50, 750, { align: 'center', width: 500 });

      doc.end();
    });

    return pdfBuffer;
  }
}
