services:
  - type: web
    name: spectra-api
    runtime: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && npx prisma db seed && node dist/src/main
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: spectra-db
          property: connectionString
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: CORS_ORIGIN
        value: https://spectra-lime.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: API_URL
        value: https://spectra-api-wq5x.onrender.com

databases:
  - name: spectra-db
    plan: free
    region: oregon
